2021-05-25 00:36:07,287 ERROR: Exception on /explore [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 135, in explore
    return render_template('index.html',title='explore',posts=posts)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\acer\microblog\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\acer\microblog\app\templates\index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "C:\Users\acer\microblog\app\templates\_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-05-25 00:36:38,199 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:36:38,669 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:38:33,092 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:38:35,342 ERROR: Exception on / [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 20, in index
    return render_template('index.html',title="home page",form=form,posts=posts)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 26, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2021-05-25 00:40:11,851 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:40:12,445 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:42:23,732 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:42:24,329 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:42:58,611 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:42:59,132 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:42:44,776 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:42:45,477 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:46:58,656 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:46:59,465 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:47:24,598 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:54:32,424 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 00:55:49,281 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-26 01:12:12,315 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-30 00:00:57,895 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-30 00:00:58,523 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-30 00:40:21,184 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-05-31 00:34:33,724 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-31 00:34:34,388 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-05-31 00:37:18,988 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-06-02 01:17:21,416 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-06-02 01:17:22,013 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:41]
2021-06-02 01:22:15,688 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:43]
2021-06-02 01:29:53,640 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-02 01:29:54,206 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-02 01:30:45,786 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:43]
2021-06-03 00:00:38,958 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-03 00:00:39,657 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-03 00:01:17,122 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:43]
2021-06-04 00:03:46,407 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-04 00:03:47,051 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:13:22,950 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:13:23,632 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:14:41,614 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:14:42,163 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:16:05,444 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:43]
