2021-06-05 01:16:19,411 ERROR: Exception on /reset_password_request [POST] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\acer\microblog\app\routes.py", line 160, in reset_password_request
    return redircet(url_for('login'))
NameError: name 'redircet' is not defined
2021-06-05 01:17:15,449 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:17:16,180 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:19:52,244 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:21:16,717 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:22:54,977 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:23:26,925 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:26:09,696 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-05 01:30:02,516 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 00:41:01,943 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 00:41:02,558 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 00:59:54,315 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 00:59:54,991 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:03:28,989 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:06:55,735 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:15:42,560 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:16:22,937 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:17:40,521 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:18:56,247 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:19:36,522 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:20:27,305 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-06 01:25:44,808 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-08 18:14:19,288 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-08 18:14:19,894 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:43]
2021-06-08 19:27:20,861 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:27:21,538 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:27:30,505 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:27:31,224 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:29:14,075 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:31:46,429 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 19:31:47,144 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 20:16:44,282 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 20:16:44,945 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 22:25:19,524 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-08 22:25:20,053 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-09 12:26:36,386 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-09 12:26:37,084 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:45]
2021-06-09 13:22:36,878 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-09 13:22:37,525 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-09 13:25:06,278 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-09 13:25:06,993 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-09 13:26:02,351 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-09 13:26:03,213 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-10 00:27:43,874 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-10 00:27:44,608 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:47]
2021-06-10 01:31:54,493 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:31:55,222 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:38:44,570 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:38:45,316 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:39:20,984 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:39:21,674 INFO: Microblog startup [in c:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:41:09,070 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:55]
2021-06-10 01:41:24,578 ERROR: Exception on / [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 27, in index
    return render_template('index.html',title=_("home page"),form=form,posts=posts.items,next_url=next_url,prev_url=prev_url)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 16, in template
    <span aria-hidden="true">&larr;</span>{{ _'(Newer posts') }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'string'
